SELECT ?propEntity ?propEntityLabel ?value ?valueLabel WHERE {
  VALUES ?person { wd:Q463299 }
  ?person ?p ?value .
  ?propEntity wikibase:directClaim ?p .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "es,en". }
}
ORDER BY ?propEntityLabel ?valueLabel
